dist: trusty
language: minimal
branches:
  except:
  - legacy
  - experimental
install:
  - rm -rf ./node_modules
  - nvm install node
  - npm --version
  - npm install cspell
  - ./node_modules/.bin/cspell --version
  # - npm install markdownlint-cli
  # - ./node_modules/.bin/markdownlint --version
script:
  - docker run -ti --rm -v $PWD:/mnt:ro dkhamsing/awesome_bot --allow-dupe --allow-redirect --skip-save-results --white-list $(paste -d, -s travis_link_check_whitelist.txt) `find . -not -path "**/node_modules/*" -not -path "./blog/themes/symphony/*" -not -path "./blog/scaffolds/*" -regex ".*\.\(md\|rst\)$"`
  - find . -not -path "**/node_modules/*" -not -path "./blog/themes/symphony/*" -not -path "./blog/scaffolds/*" -name "*.md" | grep -v  -f travis_spell_check_whitelist.txt | xargs ./node_modules/.bin/cspell -c cSpell.json
  # - ./node_modules/.bin/cspell docs/source/**/*.rst
  # - ./node_modules/.bin/markdownlint docs\source