dist: trusty
language: node_js
node_js:
  - lts/*
cache: npm
branches:
  only:
    - master # build master branch only
install:
  ## install cspell
  # - npm install cspell
  # - ./node_modules/.bin/cspell --version
  ## install markdownlint
  # - npm install markdownlint-cli
  # - ./node_modules/.bin/markdownlint --version
script:
  ## check link
  # - docker run -ti --rm -v $PWD:/mnt:ro dkhamsing/awesome_bot --allow-dupe --allow-redirect --skip-save-results --white-list $(paste -d, -s travis_link_check_whitelist.txt) `find . -not -path "**/node_modules/*" -not -path "./blog/themes/symphony/*" -not -path "./blog/scaffolds/*" -regex ".*\.\(md\|rst\)$"`
  ## check spell
  # - find . -not -path "**/node_modules/*" -not -path "./blog/themes/symphony/*" -not -path "./blog/scaffolds/*" -name "*.md" | grep -v  -f travis_spell_check_whitelist.txt | xargs ./node_modules/.bin/cspell -c cSpell.json
  # - ./node_modules/.bin/cspell docs/source/**/*.rst
  ## markdown lint 
  # - ./node_modules/.bin/markdownlint docs\source
  ## hexo
  - ./hexo-build-if-updated.sh
deploy:
  provider: pages
  edge: true
  # on:
    # condition: -n "$(git diff --name-status HEAD~1...HEAD blog)"
  local_dir: blog/public
  repo: snowme34/blog.snowme34.com
  github_token: $GITHUB_TOKEN
  fqdn: blog.snowme34.com